# Generated by Django 4.0.5 on 2022-09-23 22:00

import ckeditor.fields
import ckeditor_uploader.fields
import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('youtube_image', models.CharField(blank=True, max_length=100, null=True)),
                ('facebook_image', models.CharField(blank=True, max_length=1000, null=True)),
                ('read_min', models.CharField(default='6 mins', max_length=30)),
                ('category', models.CharField(default='coding', max_length=300)),
                ('title', models.TextField(null=True)),
                ('keyword', models.TextField(blank=True, null=True)),
                ('tags', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('content', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
                ('date_added', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('slug', models.SlugField(blank=True, max_length=100)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('PUB', 'Published')], default='DRAFT', max_length=5)),
                ('allow_comments', models.BooleanField(default=True, verbose_name='allow comments')),
                ('publish', models.DateTimeField(default=django.utils.timezone.now)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-publish',),
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=300, null=True)),
                ('date_added', models.DateTimeField(blank=True, default=datetime.datetime.now)),
            ],
        ),
        migrations.CreateModel(
            name='Syllabus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semester_course', models.TextField(default='first semester mathematics', null=True)),
                ('title', models.TextField(null=True)),
                ('table_of_content', ckeditor_uploader.fields.RichTextUploadingField()),
                ('date_added', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('slug', models.SlugField(blank=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(default='Shop', max_length=300)),
                ('title', models.TextField(null=True)),
                ('keyword', models.TextField(blank=True, null=True)),
                ('content', models.TextField(null=True)),
                ('image_url', models.URLField(blank=True, null=True)),
                ('link', models.TextField(blank=True, null=True)),
                ('iframe', models.TextField(blank=True, max_length=1000000, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
                ('date_added', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('slug', models.SlugField(blank=True, max_length=100)),
                ('allow_comments', models.BooleanField(default=True, verbose_name='allow comments')),
                ('publish', models.DateTimeField(default=django.utils.timezone.now)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-publish',),
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_pic', models.ImageField(blank=True, null=True, upload_to='profile_pics')),
                ('bio', models.TextField()),
                ('facebook_url', models.CharField(blank=True, max_length=400, null=True)),
                ('linkeld_url', models.CharField(blank=True, max_length=400, null=True)),
                ('google_url', models.CharField(blank=True, max_length=400, null=True)),
                ('whatapp_url', models.CharField(blank=True, max_length=400, null=True)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Past_Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('read_min', models.CharField(default='30 mins estimated study time', max_length=30)),
                ('tag', models.CharField(default='Past_Question', max_length=300)),
                ('title', models.TextField(null=True)),
                ('topic', models.TextField(blank=True, null=True)),
                ('keyword', models.TextField(blank=True, null=True)),
                ('table_of_content', ckeditor_uploader.fields.RichTextUploadingField()),
                ('content', ckeditor_uploader.fields.RichTextUploadingField()),
                ('learning_objective', ckeditor_uploader.fields.RichTextUploadingField(blank=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
                ('date_added', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('slug', models.SlugField(blank=True, max_length=100)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Health_Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_pic', models.ImageField(blank=True, null=True, upload_to='profile_pics')),
                ('bio', models.TextField()),
                ('facebook_url', models.CharField(blank=True, max_length=400, null=True)),
                ('linkeld_url', models.CharField(blank=True, max_length=400, null=True)),
                ('google_url', models.CharField(blank=True, max_length=400, null=True)),
                ('whatapp_url', models.CharField(blank=True, max_length=400, null=True)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Health',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('read_min', models.CharField(default='6 mins', max_length=30)),
                ('category', models.CharField(default='health tips', max_length=300)),
                ('title', models.TextField(null=True)),
                ('keyword', models.TextField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('content', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
                ('date_added', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('slug', models.SlugField(blank=True, max_length=100)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Easy_Ball',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('read_min', models.CharField(default='30 mins estimated study time', max_length=30)),
                ('tag', models.CharField(default='Past_Question', max_length=300)),
                ('title', models.TextField(null=True)),
                ('topic', models.TextField(blank=True, null=True)),
                ('keyword', models.TextField(blank=True, null=True)),
                ('content', ckeditor_uploader.fields.RichTextUploadingField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
                ('date_added', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('slug', models.SlugField(blank=True, max_length=100)),
                ('allow_comments', models.BooleanField(default=True, verbose_name='allow comments')),
                ('publish', models.DateTimeField(default=django.utils.timezone.now)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-publish',),
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('email', models.EmailField(max_length=254)),
                ('body', ckeditor_uploader.fields.RichTextUploadingField(null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='posts.blog')),
            ],
        ),
        migrations.CreateModel(
            name='Brainy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('read_min', models.CharField(default='6 mins', max_length=30)),
                ('tag', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('category', models.CharField(default='coding', max_length=300)),
                ('title', models.TextField(max_length=500, null=True)),
                ('keyword', models.TextField(default='maths,physics,chemistry,engineering', max_length=1000)),
                ('description', models.TextField(blank=True, null=True)),
                ('content', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True)),
                ('date_added', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('slug', models.SlugField(blank=True, max_length=100)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('PUB', 'Published')], default='DRAFT', max_length=5)),
                ('allow_comments', models.BooleanField(default=True, verbose_name='allow comments')),
                ('publish', models.DateTimeField(default=django.utils.timezone.now)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-publish',),
            },
        ),
        migrations.CreateModel(
            name='Ask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(default='coding', max_length=300)),
                ('title', models.TextField(null=True)),
                ('keyword', models.TextField(blank=True, null=True)),
                ('content', ckeditor_uploader.fields.RichTextUploadingField(null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
                ('date_added', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('slug', models.SlugField(blank=True, max_length=100)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('iframe', models.TextField(blank=True, max_length=1000000, null=True)),
                ('iframe1', models.TextField(blank=True, max_length=1000000, null=True)),
                ('iframe2', models.TextField(blank=True, max_length=1000000, null=True)),
                ('youtube_image', models.CharField(blank=True, max_length=100, null=True)),
                ('facebook_image', models.CharField(blank=True, max_length=1000, null=True)),
                ('read_min', models.CharField(default='6 mins', max_length=30)),
                ('category', models.CharField(default='coding', max_length=300)),
                ('title', models.TextField(null=True)),
                ('keyword', models.TextField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('tags', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True)),
                ('content', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
                ('date_added', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('date_modified', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('slug', models.SlugField(blank=True, max_length=100)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('PUB', 'Published')], default='DRAFT', max_length=5)),
                ('allow_comments', models.BooleanField(default=True, verbose_name='allow comments')),
                ('publish', models.DateTimeField(default=django.utils.timezone.now)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-publish',),
            },
        ),
        migrations.CreateModel(
            name='Academic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('read_min', models.CharField(default='6 mins', max_length=30)),
                ('tag', models.CharField(default='coding', max_length=300)),
                ('title', models.TextField(null=True)),
                ('topic', models.TextField(blank=True, null=True)),
                ('keyword', models.TextField(blank=True, null=True)),
                ('table_of_content', ckeditor_uploader.fields.RichTextUploadingField()),
                ('content', ckeditor_uploader.fields.RichTextUploadingField()),
                ('learning_objective', ckeditor_uploader.fields.RichTextUploadingField(blank=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
                ('date_added', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('slug', models.SlugField(blank=True, max_length=100)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
