# Generated by Django 4.0.5 on 2022-10-01 08:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_remove_article_iframe_remove_article_iframe1_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='easy_ball',
            name='image',
        ),
        migrations.RemoveField(
            model_name='easy_ball',
            name='read_min',
        ),
    ]
