# Generated by Django 4.0.5 on 2022-10-01 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_remove_easy_ball_image_remove_easy_ball_read_min'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='easy_ball',
            name='topic',
        ),
        migrations.AlterField(
            model_name='easy_ball',
            name='title',
            field=models.CharField(max_length=150, null=True),
        ),
    ]
