# Generated by Django 4.0.5 on 2022-10-01 11:43

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_remove_easy_ball_topic_alter_easy_ball_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='easy_ball',
            name='tag',
        ),
        migrations.AddField(
            model_name='easy_ball',
            name='tags',
            field=ckeditor.fields.RichTextField(blank=True),
        ),
    ]
