# Generated by Django 4.0.5 on 2022-10-19 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0007_alter_easy_ball_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='summer_content',
            field=models.TextField(blank=True),
        ),
    ]
