# Generated by Django 4.0.5 on 2022-10-19 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0008_blog_summer_content'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='youtube_image',
        ),
        migrations.AlterField(
            model_name='blog',
            name='tags',
            field=models.TextField(blank=True, null=True),
        ),
    ]
