# Generated by Django 4.0.5 on 2022-10-21 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0012_remove_html_ide_html_level_html_summer_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='python',
            name='level',
            field=models.TextField(default='Easy'),
        ),
        migrations.AlterField(
            model_name='html',
            name='level',
            field=models.TextField(default='Easy'),
        ),
    ]
