# Generated by Django 4.0.5 on 2022-10-25 15:10

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0014_python_summer_content'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='python',
            options={'ordering': ('publish',)},
        ),
        migrations.RemoveField(
            model_name='python',
            name='ide',
        ),
        migrations.AlterField(
            model_name='python',
            name='content',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True),
        ),
    ]
