# Generated by Django 4.0.5 on 2022-10-25 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0015_alter_python_options_remove_python_ide_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='python',
            name='tags',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
