# Generated by Django 4.0.5 on 2022-11-03 08:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0017_alter_python_level_alter_python_tags'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='facebook_image',
        ),
    ]
