# Generated by Django 4.0.5 on 2022-12-04 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0021_javascript'),
    ]

    operations = [
        migrations.AlterField(
            model_name='javascript',
            name='tags',
            field=models.TextField(blank=True, null=True),
        ),
    ]
