# Generated by Django 4.0.5 on 2022-12-04 21:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0022_alter_javascript_tags'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='date_added',
            new_name='updated',
        ),
        migrations.RenameField(
            model_name='blog',
            old_name='date_added',
            new_name='updated',
        ),
        migrations.RenameField(
            model_name='brainy',
            old_name='date_added',
            new_name='updated',
        ),
        migrations.RemoveField(
            model_name='article',
            name='date_modified',
        ),
    ]
