# Generated by Django 4.0.5 on 2023-01-01 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0025_blog_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='brainy',
            name='summer_content',
            field=models.TextField(blank=True, null=True),
        ),
    ]
