# Generated by Django 4.0.5 on 2023-01-01 11:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0026_brainy_summer_content'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ask',
            name='author',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='post',
        ),
        migrations.DeleteModel(
            name='Syllabus',
        ),
        migrations.DeleteModel(
            name='Ask',
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
