# Generated by Django 4.1.5 on 2023-01-05 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0027_remove_ask_author_remove_comment_post_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="article",
            name="category",
            field=models.CharField(default="blog", max_length=300),
        ),
    ]
