# Generated by Django 4.1.5 on 2023-01-12 12:05

from django.db import migrations
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ("taggit", "0005_auto_20220424_2025"),
        ("posts", "0029_article_body_article_tag_alter_article_title"),
    ]

    operations = [
        migrations.AddField(
            model_name="python",
            name="tag",
            field=taggit.managers.TaggableManager(
                help_text="A comma-separated list of tags.",
                through="taggit.TaggedItem",
                to="taggit.Tag",
                verbose_name="Tags",
            ),
        ),
    ]
