# Generated by Django 4.1.5 on 2023-01-12 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0030_python_tag"),
    ]

    operations = [
        migrations.AddField(
            model_name="python",
            name="status",
            field=models.CharField(
                choices=[("DRAFT", "Draft"), ("PUB", "Published")],
                default="DRAFT",
                max_length=5,
            ),
        ),
    ]
