# Generated by Django 4.1.5 on 2023-01-13 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0031_python_status"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="python",
            name="status",
        ),
        migrations.AddField(
            model_name="python",
            name="draft",
            field=models.BooleanField(default="False"),
        ),
    ]
