# Generated by Django 4.1.5 on 2023-01-13 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0032_remove_python_status_python_draft"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="blog",
            name="status",
        ),
        migrations.AddField(
            model_name="blog",
            name="draft",
            field=models.BooleanField(default=False),
        ),
    ]
