# Generated by Django 4.1.5 on 2023-01-13 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0033_remove_blog_status_blog_draft"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="php",
            name="status",
        ),
        migrations.AddField(
            model_name="php",
            name="draft",
            field=models.BooleanField(default=False),
        ),
    ]
