# Generated by Django 4.1.5 on 2023-01-13 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0034_remove_php_status_php_draft"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="article",
            name="status",
        ),
        migrations.AddField(
            model_name="article",
            name="draft",
            field=models.BooleanField(default=False),
        ),
    ]
