# Generated by Django 4.1.5 on 2023-01-13 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0035_remove_article_status_article_draft"),
    ]

    operations = [
        migrations.AlterField(
            model_name="article",
            name="draft",
            field=models.BooleanField(default=True),
        ),
    ]
