# Generated by Django 4.1.5 on 2023-01-26 11:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0037_loggedinuser"),
    ]

    operations = [
        migrations.DeleteModel(
            name="LoggedInUser",
        ),
    ]
