# Generated by Django 4.1.5 on 2023-03-23 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0040_blog_url_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blog",
            name="url_image",
            field=models.URLField(blank=True, max_length=200000000, null=True),
        ),
    ]
