# Generated by Django 4.1.5 on 2023-03-26 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0041_alter_blog_url_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="article",
            name="url_image",
            field=models.URLField(blank=True, max_length=200000000, null=True),
        ),
    ]
