# Generated by Django 4.1.5 on 2023-03-26 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0042_article_url_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="article",
            name="url_image",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="blog",
            name="url_image",
            field=models.URLField(blank=True, null=True),
        ),
    ]
