# Generated by Django 4.1.5 on 2023-08-06 18:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0044_brainy_url_image"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="brainy",
            name="url_image",
        ),
    ]
