# Generated by Django 4.1.5 on 2023-08-09 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0045_remove_brainy_url_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blog",
            name="slug",
            field=models.SlugField(blank=True, max_length=100, unique=True),
        ),
    ]
