# Generated by Django 4.1.5 on 2023-08-25 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0047_alter_blog_title_flutter"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blog",
            name="slug",
            field=models.SlugField(blank=True, max_length=150, unique=True),
        ),
    ]
