# Generated by Django 4.1.5 on 2023-08-28 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0050_alter_article_slug_alter_article_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='academic',
            name='slug',
            field=models.SlugField(blank=True, max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='academic',
            name='title',
            field=models.TextField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='easy_ball',
            name='slug',
            field=models.SlugField(blank=True, max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='easy_ball',
            name='title',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='html',
            name='slug',
            field=models.SlugField(blank=True, max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='html',
            name='title',
            field=models.TextField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='php',
            name='slug',
            field=models.SlugField(blank=True, max_length=150, unique=True),
        ),
        migrations.AlterField(
            model_name='php',
            name='title',
            field=models.TextField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='python',
            name='slug',
            field=models.SlugField(blank=True, max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='python',
            name='title',
            field=models.TextField(max_length=255, null=True),
        ),
    ]
