# Generated by Django 4.1.5 on 2023-08-28 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0051_alter_academic_slug_alter_academic_title_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='academic',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='blog',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='brainy',
            name='slug',
            field=models.SlugField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='brainy',
            name='title',
            field=models.TextField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='easy_ball',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='flutter',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='health',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='html',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='javascript',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='javascript',
            name='title',
            field=models.TextField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='past_question',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='past_question',
            name='title',
            field=models.TextField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='php',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='python',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='shop',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='shop',
            name='title',
            field=models.TextField(max_length=255, null=True),
        ),
    ]
