# Generated by Django 4.1.5 on 2023-08-29 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0052_alter_academic_slug_alter_article_slug_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PageVisit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_url', models.CharField(max_length=200, unique=True)),
                ('visit_count', models.PositiveIntegerField(default=0)),
            ],
        ),
    ]
