# Generated by Django 4.1.5 on 2023-08-29 21:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0053_pagevisit'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PageVisit',
        ),
    ]
