# Generated by Django 4.1.5 on 2023-09-01 20:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0054_delete_pagevisit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='javascript',
            name='date_added',
        ),
        migrations.RemoveField(
            model_name='javascript',
            name='status',
        ),
        migrations.AlterField(
            model_name='javascript',
            name='publish',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
    ]
