# Generated by Django 4.1.5 on 2023-09-01 20:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0055_remove_javascript_date_added_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='brainy',
            name='status',
        ),
    ]
