# Generated by Django 4.1.5 on 2023-01-26 12:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("accounts", "0002_alter_loggedinuser_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="loggedinuser",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="logged_in_user",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
