from django.urls import path
from . import views
from .views import *
from .views import  HealthPostView
from django.contrib.auth.models import User,auth
from django.contrib.sitemaps.views import sitemap
from django.contrib.staticfiles.storage import staticfiles_storage
from django.views.generic.base import RedirectView
from .sitemaps import ( GeneralSitemap,HealthSitemap,PythonSitemap,HtmlSitemap,BrainySitemap,Easy_BallSitemap,StaticSitemap,ShopSitemap,FlutterSitemap,
    BlogSitemap, ArticleSitemap, 
)

sitemaps = {
    'blogs': BlogSitemap,
    'articles': ArticleSitemap,
}

urlpatterns = [

    path('sitemap-flutter.xml', sitemap, {'sitemaps': {'flutters': FlutterSitemap}}, name='sitemap_flutter'),
    path('sitemap-static.xml', sitemap, {'sitemaps': {'statics': StaticSitemap}}, name='sitemap_static'),
    path('sitemap-shop.xml', sitemap, {'sitemaps': {'shops': ShopSitemap}}, name='sitemap_shop'),
    path('sitemap-easy_ball.xml', sitemap, {'sitemaps': {'easy_ball': Easy_BallSitemap}}, name='sitemap_easy_ball'),
    path('sitemap-brainy.xml', sitemap, {'sitemaps': {'brainys': BrainySitemap}}, name='sitemap_brainy'),
    path('sitemap-html.xml', sitemap, {'sitemaps': {'htmls': HtmlSitemap}}, name='sitemap_html'),
    path('sitemap-pyton.xml', sitemap, {'sitemaps': {'pythons':PythonSitemap}}, name='sitemap_python'),
    path('sitemap-general.xml', sitemap, {'sitemaps': {'general': GeneralSitemap}}, name='sitemap_general'),
    path('sitemap-health.xml', sitemap, {'sitemaps': {'healths':HealthSitemap}}, name='sitemap_health'),
    path('sitemap-blog.xml', sitemap, {'sitemaps': {'blogs': BlogSitemap}}, name='sitemap_blog'),
    path('sitemap-article.xml', sitemap, {'sitemaps': {'articles': ArticleSitemap}}, name='sitemap_article'),
    path('get_titles/', views.get_titles, name='get_titles'),
    path('search/', views.search_view, name='search'),
    path('favicon.ico', RedirectView.as_view(url=staticfiles_storage.url('images/icons/favicon.ico'))),
    path('adminpost/', views.admin_article_view, name='adminpost'),
    path('users_post/', views.user_article_view, name='add_blog'),
    path('html/',views.Html_Views,name='htmls'),
    path('php/',views.PhpListView,name='phps'),
    path('php/<slug:slug>/',views.Php_Detail,name='php_detail'),
    path('python/',views.PythonListView,name = 'pythons'),
    path('about-us',views.AboutView,name='about'),
    #path('ads.txt', views.Ads,name='ads'),
    path('python/<slug:slug>/',views.Python_View,name='python'),
    path('html/<slug:slug>/',views.Html_View,name='html'),
    path('scripts/<slug:slug>/',views.Javascript_View,name='javascript'),
    path('lesson/', views.Lesson_View,name='lesson'),
    path('guest_post/', views.Guestpost_View,name='guest_post'),
    path('shops/<slug:slug>',views.Shop_Detail,name='shops'),
    path('shop/',views.Shop_View,name='shop'),
    path('easy-football/<slug:slug>',views.Ball_Detail,name='ball-detail'),
    path('easy/football/',views.Ball_View,name="ball-list"),
    path('success/', ContactSuccessView.as_view(), name="success"),
    path('contact-us/', ContactView.as_view(), name="contact"),
    path('join/us',views.join_us,name='login_page'),
    path('academics/<slug:slug>',views.edu_detail,name='edu_detail'),
    path('past-questions/<slug:slug>',views.Past_Detail,name='past_detail'),
    path('year/one/first_semester/',views.first_semester,name='first_semester'),
    path('edit-profile/',UserEditView.as_view(),name='edit_profile'),
    path('edit-author/',views.StaffEditView,name='edit_author'),
    path('edit-php/<slug:slug>',UpdatePhpView.as_view(),name='update_php'),
    path('update_flutter/<slug:slug>',Update_Flutter.as_view(),name='update_flutter'),
    #this ask question url
    path('ask/',views.Ask_View,name = 'ask'),
    path('edit-ball/<slug:slug>',UpdateBallView.as_view(),name='edit_ball'),
    path('edit-python/<slug:slug>',views.UpdatePythonView,name='edit_python'),
    path('edit-past/<slug:slug>',UpdatePastView.as_view(),name='edit_past'),
    path('accounts/profile/',views.ProfileView,name='my_profile'),
    path('password-changed/',views.PasswordChangedView,name='password_changed'),
    path('addhealthpost',views.HealthPost,name='addhealthpost'),
    path('academics',views.AcademicPost,name='add_academic'),
    path('edit-edu/<slug:slug>',views.UpdateAcademic,name='edit_academic'),
    path('past/questions',views.Past_QuestionView,name='past_questions'),
    path('django/edit/<slug:slug>',views.UpdatePostView,name='edit_post'),
    path('meinem/edit/<slug:slug>',views.UpdateArticlePostView,name='edit_blog'),
    path('mypost/edit/<slug:slug>',views.UpdateSchoolPostView,name='edit_school_post'),
    path('healthy/edit/<slug:slug>',views.UpdateHealthPostView,name='edit_health_post'),
    path('schoolpost',views.schoolpost,name='schoolpost'),
    path('health/',views.HealthPostView,name='health'),
    path('article',views.article, name='article'),
    path('javascript',views.Script_List, name='script_list'),
    path('django/',views.Blog_List, name='blog'),
    path('flutters',views.flutter_list, name='flutter_list'),
    path('',views.index, name='index'),
    path('category',views.category,name='category'),
    path('signup',views.signup, name='signup'),
    path('requestpost',views.requestpost, name='requestpost'),
    path('login',views.login_user, name='login'),
    path('logout',views.logout, name='logout'),
    path('privacy',views.privacy, name='privacy'),
    path('terms',views.terms, name='terms'),
    path('categories/<str:cate>',views.categories, name='categories'),
    path('categories_health/<str:categories>',views.category_health, name='category_health'),
    path('categories/<slug:slug>/delete',DeletePostView.as_view(), name='delete_post'),
    path('deletepost/<slug:slug>/delete',DeleteHealthPostView.as_view(), name='delete_health_post'),
    path('delete_my_post/<slug:slug>/delete',DeleteSchoolPostView.as_view(), name='delete_school_post'),
    path('topu/<slug:slug>/delete',DeleteArticlePostView.as_view(), name='delete_blog'),
    path('blog/<slug:slug>',views.my_blog, name='my_blog'),
    path('detail/<slug:slug>',views.Detail_View, name='detail'),
    path('flutter/<slug:slug>',views.flutter_detail, name='flutter_detail'),
    path('healthy/<slug:slug>',views.DetailHealthView,name='health_tips'),
    path('brainhub/<slug:slug>',views.brainhub, name='brainhub'),
    path('staff/profile/',Staff_Profile_View.as_view(),name='create_profile'),
    path('post/',AddSchoolPostView.as_view(),name='addschoolpost'),
    path('add_py',AddPyView.as_view(),name='add_py'),
    path('add-ball',AddBallView.as_view(),name='add_ball'),
    path('addpost',AddPostView.as_view(),name='addpost'),
    path('addflutter',AddFlutterView.as_view(),name='add_flutter'),
    path('addphp',AddPhpView.as_view(),name='add_php'),
    path('password/',ChangePasswordView.as_view(),name='change_password'),
    path('addcategory',AddCategoryView.as_view(),name='addcategory'),

]
